### PR TITLE
Improved UI scaling, and also arena now always has the same scale as the host window.

### PR DESCRIPTION
**Pull request by MarcellVokk**

### CODE REVIEW

**Review by Ravo92 — CHANGES_REQUESTED** [review]
Please recheck this file

**Comment by MarcellVokk** [comment]
Sorry which file?

**Comment by Ravo92** [comment]
> Sorry which file?

[Settings_RotwkGeneral.xaml.cs](https://github.com/Ravo92/Patch-2.22-Launcher/pull/47/commits/124120826f22dc04a888fb013ce39e7f7e6532ca#diff-517be5a8e5f15ade6dc9a74213d8c179c8fc90408e962709b6f16786bb2e8bf0)

**Comment by MarcellVokk** [comment]
No idea how that hapened... Fixed now

**Pull request merged**
