### PR TITLE
Don't try to create a release if it's a PR, since it will fail the pipeline

### PR DESCRIPTION
**Pull request by dginovker**
This will still run the CI/CD to make sure it builds, but it won't make an artifact

### CODE REVIEW

**Comment by Ravo92** [comment]
Can you please further explain what this code is doing or not doing? I do not understand this if case.

**Comment by dginovker** [comment]
Basically CICD won't try to publish a new release at https://github.com/Ravo92/Patch-2.22-Launcher/releases unless it's running code on the `main` branch.

If you look at https://github.com/Ravo92/Patch-2.22-Launcher/pull/26 you can see the CICD failed in that PR, because the PR tried to automatically create a new release, but since the PR came from me and I don't have permission to make a new release, the pipeline failed.

In this PR, the pipeline isn't failing, because it's not trying to create a new release

**Comment by dginovker** [comment]
Once you merge this PR though (or any future PR that has this code), the `main` will still kick off and make a new release afterwards

**Comment by Ravo92** [comment]
Thank you kind sir.

**Pull request merged**
