### PR TITLE
Update readme to include an image and moddb link

### PR DESCRIPTION
**Pull request by dginovker**
See example of what it looks like https://github.com/dginovker/Patch-2.22-Launcher/tree/downloadsinreadme

### CODE REVIEW

**Comment by dginovker** [comment]
Creating PR since I've linked this Github repo in a few places online so Google boosts its SEO. People might be finding it and looking for a download link

**Comment by dginovker** [comment]
I'll make a nice image like this one in the future, just at work atm
image

**Comment by dginovker** [comment]
Gonna merge, CI failed for permission issues lol

**Comment by Ravo92** [comment]
Thank you!

**Pull request merged**
