### PR TITLE
Major refactoring of core systems, and new patch selection UI components. **Work in progress!**

### PR DESCRIPTION
**Pull request by MarcellVokk**
Major refactoring of core systems, and new patch selection UI components.
**Work in progress!**

### CODE REVIEW

**Comment by Ravo92** [comment]
Please check my latest changes and feedback here: https://github.com/Ravo92/Patch-2.22-Launcher/pull/46/commits/ef43b2fae825ffdc7a4a8edc6a72961691fec353

**Comment by Ravo92** [comment]
Forgot some parts...
https://github.com/Ravo92/Patch-2.22-Launcher/pull/46/commits/6e137c3b6d0b12785be5c228a26d2c3764264c6e

**Comment by MarcellVokk** [comment]
I took a quick look, and all seems fine, using enums instead of integers to specify the game is a good idea.

But, I have a problem with the naming convention you are using, it's inconsistent. Here are my suggestions:

- The `AvailableBFMEGames` enum should be named `BfmeGame` or `BfmeGames`
- The `availableBFMEGames` parameter in functions should be renamed to `game` in all functions that use it
- `BFMELaunchManager`, `BFMERegistryManager`, `BFMESettingsManager` and all classes that use the `BFME<Something>` naming convention should be renamed `Bfme<Something>`, so `BfmeLaunchManager`, `BfmeRegistryManager`, etc...
- `Settings_BFME1General`, `Settings_BFME1Repair` and all settings pages that use the `Settings_<BFMEGAME><Something>` naming convention should be renamed `Settings_<Bfmegame><Something>`, so `Settings_Bfme1General`, `Settings_Bfme1Repair`, etc...

The reason behind this is to maintain naming consistency across the project, since all other static classes follow the "UpperCamelCase" naming convention (eg.: `SystemDisplayManager`, `SystemInputManager`, `LauncherStateManager`, `LauncherUpdateManager`, etc...)

**Comment by MarcellVokk** [comment]
Looks good!

**Pull request merged**
